# Generated by Django 2.0.5 on 2018-07-01 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_remove_profile_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=800)),
                ('color', models.TextField(max_length=10)),
                ('background_color', models.TextField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='userboardid',
            name='board_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.UserBoardId'),
        ),
    ]
