# Generated by Django 2.0.5 on 2018-07-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_auto_20180701_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
